### ISSUE TITLE
publish new version to npm

### ISSUE THREAD

**Issue by maks** [maks/blogdown#7]
Hi @mantoni 
I'd like to publish my updated version to npm, would you mind [adding me as a maintainer of the module](https://docs.npmjs.com/cli/owner) ?
My username on npm is: `maks`

**Comment by mantoni** [comment]
I still use this project occasionally and will maybe need to make changes in the future myself. It would be annoying if the npm package was updated from two different repositories. If you could contribute your changes back to the repo here, we can collaborate on the work and publish from a common code base.

**Comment by maks** [comment]
@mantoni yes, I'd be very happy to do that - I only started the fork based on your previous comment that you didn't have time to work on it and that I should maintain it.
I'll open PRs against your repo.

**Comment by mantoni** [comment]
Cool. I actually offered to grant you push access 👍

**Comment by maks** [comment]
Oh! Sorry I completely misunderstood, thanks!

**Comment by maks** [comment]
I've started putting through the PRs, they are "stacked", so are intended to me merged in order, hope thats ok.
